[project]
name = "everest"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "autoflake>=2.3.1",
    "black>=25.1.0",
    "cel-python>=0.2.0",
    "isort>=6.0.1",
    "jinja2>=3.1.6",
]
