[package]
name = "num"
version = "0.1.0"
authors = ["satreix <satreix@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
pyo3-build-config = { workspace = true }

[dependencies]
pyo3 = { workspace = true, features = ["extension-module"] }
rayon = { workspace = true }
