[package]
name = "web"
version = "0.1.0"
authors = ["satreix <satreix@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
iron = "0.6.1"
iron-slog = "0.0.2"
router = "0.6.0"
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"

[dev-dependencies]
iron-test = "0.6.0"
