[package]
name = "web"
version = "0.1.0"
authors = ["satreix <satreix@gmail.com>"]
edition = "2021"

[dependencies]
askama = { workspace = true }
askama_warp = { workspace = true }
slog = { workspace = true }
slog-async = { workspace = true }
slog-term = { workspace = true }
tokio = { workspace = true }
warp = { workspace = true }
