[package]
name = "web"
version = "0.1.0"
authors = ["satreix <satreix@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
askama_warp = "0.13.0"
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.1"
tokio = "1"
warp = { version = "0.3.7", default-features = false }
