name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - '*.*.*'
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
    name: check - (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      # Python rules use host install still.
      - uses: actions/setup-python@v1
      - run: python --version

      - name: Install bazelisk
        run: ./tools/ci/install_bazelisk.sh v1.7.5 ${{ matrix.platform }}

      - name: Test
        run: ./bin/bazel test //...

      - name: Build
        run: ./bin/bazel build //...
