name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - '*.*.*'
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
    name: check - (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      # Ruby rules use host install still: https://github.com/bazelruby/rules_ruby/issues/112
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.107.0

      - name: Install bazelisk
        run: ./tools/ci/install_bazelisk.sh v1.11.0 ${{ matrix.platform }}

      - name: Test
        run: ./bin/bazel test --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} //...

      - name: Build
        run: ./bin/bazel build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} //...
