name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    name: check - (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'PR commits + 1'
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: 'Checkout PR branch and PR commits'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      # https://github.com/tweag/rules_haskell/issues/704
      - name: "[Haskell] Install required packages"
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -yy libtinfo5
          sudo apt-get clean
        if: ${{ matrix.os == 'ubuntu-latest' }}

      # Ruby rules use host install still: https://github.com/bazelruby/rules_ruby/issues/112
      - name: "[Ruby] Install Ruby"
        uses: ruby/setup-ruby@v1.144.1

      - name: Install bazelisk
        run: ./tools/ci/install_bazelisk.sh v1.16.0 ${{ matrix.os }}

      - name: Test
        env:
          BASE_REF: ${{ github.event.pull_request.base.sha }}
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: ./tools/ci/pr.sh
