name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - '*.*.*'
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    name: check - (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # https://github.com/tweag/rules_haskell/issues/704
      - name: "[Haskell] Install required packages"
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -yy libtinfo5
          sudo apt-get clean
        if: ${{ matrix.os == 'ubuntu-latest' }}

      # Ruby rules use host install still: https://github.com/bazelruby/rules_ruby/issues/112
      - name: "[Ruby] Install Ruby"
        uses: ruby/setup-ruby@v1.149.0

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Copy .bazelrc
        run: cp tools/ci/bazel.rc $HOME/.bazelrc

      - name: Test
        run: bazel test --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }} //...
